name: Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
          
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction
        
      - name: Run Pint
        run: vendor/bin/pint --test

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]
        laravel: [10.*, 11.*, 12.*]
        include:
          - laravel: 10.*
            testbench: 8.*
            pest: 2.*
            phpunit: 10.*
          - laravel: 11.*
            testbench: 9.*
            pest: 3.*
            phpunit: 11.*
          - laravel: 12.*
            testbench: 10.*
            pest: 3.*
            phpunit: 11.*
        exclude:
          - laravel: 12.*
            php: 8.2

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Remove composer.lock
        run: rm -f composer.lock

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer require --dev "orchestra/testbench:${{ matrix.testbench }}" "pestphp/pest:${{ matrix.pest }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Execute tests
        run: ./vendor/bin/pest --configuration=phpunit.xml